const SET_USER = 'SET_USER'
const SET_USERS = 'SET_USERS'
const UPDATE_USER = 'UPDATE_USER'
const UPDATE_USER_ERR = 'UPDATE_USER_ERR'

export {
  SET_USERS,
  SET_USER,
  UPDATE_USER,
  UPDATE_USER_ERR
}
